# Generated by Django 5.1.5 on 2025-01-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
